### ISSUE TITLE
Docker fails to build

### ISSUE THREAD

**Issue by AliRezaBeitari** [hunter-io/wappalyzer-api#6]
When Docker reaches the 7th step (`RUN npm i`), it fails to build. Here is the output:

```
 => ERROR [7/9] RUN npm i                                                                       102.2s
------
 > [7/9] RUN npm i:
#9 81.68
#9 81.68 > cld@2.6.0 install /app/node_modules/wappalyzer/node_modules/cld
#9 81.68 > node-gyp rebuild
#9 81.68
#9 83.98 make: Entering directory '/app/node_modules/wappalyzer/node_modules/cld/build'
#9 83.99   CXX(target) Release/obj.target/cld-c/deps/cld/internal/cldutil.o
#9 84.30   CXX(target) Release/obj.target/cld-c/deps/cld/internal/cldutil_shared.o
#9 84.59   CXX(target) Release/obj.target/cld-c/deps/cld/internal/compact_lang_det.o
#9 84.73   CXX(target) Release/obj.target/cld-c/deps/cld/internal/compact_lang_det_hint_code.o
#9 85.20   CXX(target) Release/obj.target/cld-c/deps/cld/internal/compact_lang_det_impl.o
#9 86.02   CXX(target) Release/obj.target/cld-c/deps/cld/internal/debug.o
#9 86.48   CXX(target) Release/obj.target/cld-c/deps/cld/internal/fixunicodevalue.o
#9 86.53   CXX(target) Release/obj.target/cld-c/deps/cld/internal/generated_entities.o
#9 86.55   CXX(target) Release/obj.target/cld-c/deps/cld/internal/generated_language.o
#9 86.61   CXX(target) Release/obj.target/cld-c/deps/cld/internal/generated_ulscript.o
#9 86.65   CXX(target) Release/obj.target/cld-c/deps/cld/internal/getonescriptspan.o
#9 87.41   CXX(target) Release/obj.target/cld-c/deps/cld/internal/lang_script.o
#9 87.62   CXX(target) Release/obj.target/cld-c/deps/cld/internal/offsetmap.o
#9 87.98   CXX(target) Release/obj.target/cld-c/deps/cld/internal/scoreonescriptspan.o
#9 88.64   CXX(target) Release/obj.target/cld-c/deps/cld/internal/tote.o
#9 88.80   CXX(target) Release/obj.target/cld-c/deps/cld/internal/utf8statetable.o
#9 89.56   CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld_generated_cjk_uni_prop_80.o
#9 90.04   CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_cjk_compatible.o
#9 90.08   CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld_generated_cjk_delta_bi_32.o
#9 90.24   CXX(target) Release/obj.target/cld-c/deps/cld/internal/generated_distinct_bi_0.o
#9 90.27   CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_quad0122.o
#9 95.71   CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_deltaocta0122.o
#9 96.73   CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_deltaoctachrome.o
#9 96.80   CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_distinctocta0122.o
#9 96.93   CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_distinctoctachrome.o
#9 96.97   CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_quadchrome_16.o
#9 97.70   CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_quadchrome_2.o
#9 99.02   CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld_generated_score_quad_octa_0122.o
#9 99.07   CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld_generated_score_quad_octa_2.o
#9 99.10   AR(target) Release/obj.target/deps/cld/cld-c.a
#9 99.15   COPY Release/cld-c.a
#9 99.17   CXX(target) Release/obj.target/cld/src/constants.o
#9 100.2   CXX(target) Release/obj.target/cld/src/cld.o
#9 100.4 ../src/cld.cc:5:12: error: 'terminate_handler' has not been declared in 'std'
#9 100.4     5 | using std::terminate_handler;
#9 100.4       |            ^~~~~~~~~~~~~~~~~
#9 100.4 ../src/cld.cc:6:12: error: 'unexpected_handler' has not been declared in 'std'
#9 100.4     6 | using std::unexpected_handler;
#9 100.4       |            ^~~~~~~~~~~~~~~~~~
#9 100.9 make: Leaving directory '/app/node_modules/wappalyzer/node_modules/cld/build'
#9 100.9 make: *** [cld.target.mk:115: Release/obj.target/cld/src/cld.o] Error 1
#9 100.9 gyp ERR! build error
#9 100.9 gyp ERR! stack Error: `make` failed with exit code: 2
#9 100.9 gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
#9 100.9 gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
#9 100.9 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
#9 100.9 gyp ERR! System Linux 5.15.49-linuxkit
#9 100.9 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
#9 100.9 gyp ERR! cwd /app/node_modules/wappalyzer/node_modules/cld
#9 100.9 gyp ERR! node -v v14.21.3
#9 100.9 gyp ERR! node-gyp -v v5.1.1
#9 100.9 gyp ERR! not ok
#9 102.0 npm ERR! code ELIFECYCLE
#9 102.0 npm ERR! errno 1
#9 102.0 npm ERR! cld@2.6.0 install: `node-gyp rebuild`
#9 102.0 npm ERR! Exit status 1
#9 102.0 npm ERR!
#9 102.0 npm ERR! Failed at the cld@2.6.0 install script.
#9 102.0 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#9 102.1
#9 102.1 npm ERR! A complete log of this run can be found in:
#9 102.1 npm ERR!     /home/node/.npm/_logs/2023-04-15T16_05_26_161Z-debug.log
------
executor failed running [/bin/sh -c npm i]: exit code: 1
```

**Docker version 20.10.23, build 7155243**
**System Version: macOS 13.3.1 (22E261)**
**Kernel Version: Darwin 22.4.0**

**Comment by antoinefink** [comment]
Should now work!
